


POST  http://localhost:3096/api/users/register
Content-Type: application/json

{

    "name": "juan",
    "code":"123456",
    "password": "123456789",
    "email": "jjjj.GR2004@gmail.com"
}

### Validar email con código
POST http://localhost:3096/api/users/validation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U4MjRkZThmYzA4NDkwZGY2M2RlODEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MzI2NzAzOCwiZXhwIjoxNzQzMjc0MjM4fQ.M30qaly1uPG1j0V__LBqFHu0NH1cBQMNw2Pwymnh4gc
Content-Type: application/json

{
  "code": "123456"
}


###
POST  http://localhost:3096/api/users/login
Content-Type: application/json

{
   "password": "123456789",
    "email": "jjjj.GR2004@gmail.com"
}

###
PATCH http://localhost:3096/api/storage HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="img.jpg"
Content-Type: image/jpg

< ./img.jpg
--Boundry--


###
PATCH http://localhost:3096/api/users/onboardingUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U4MjRkZThmYzA4NDkwZGY2M2RlODEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MzI2NzAzOCwiZXhwIjoxNzQzMjc0MjM4fQ.M30qaly1uPG1j0V__LBqFHu0NH1cBQMNw2Pwymnh4gc
Content-Type: application/json

{
  "name": "Juna",
  "apellidos": "Gonzale",
  "nif": "12345678Z"
}

### PATCH - Onboarding empresa
PATCH http://localhost:3096/api/users/onboardingCompany
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U4MjRkZThmYzA4NDkwZGY2M2RlODEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MzI2NzAzOCwiZXhwIjoxNzQzMjc0MjM4fQ.M30qaly1uPG1j0V__LBqFHu0NH1cBQMNw2Pwymnh4gc
Content-Type: application/json

{
  "companyName": "Empresa S.L.",
  "cif": "B12345678",
  "address": "Calle Empresa 1, Madrid",
  "phone": "912345678",
  "isFreelance": false
}
